INSERT INTO PERSON(ID,NAME,COUNTRY,BIRTH_DATE)
VALUES(10001, 'Adrian', 'Poland', sysdate());
INSERT INTO PERSON(ID,NAME,COUNTRY,BIRTH_DATE)
VALUES(10002, 'Beata', 'Poland', sysdate());
INSERT INTO PERSON(ID,NAME,COUNTRY,BIRTH_DATE)
VALUES(10003, 'Douglas', 'Grate Britain', sysdate());